const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { parseOpenCvYaml } = require('../services/calibration/opencvYaml');
const { inspectCalibrationFile } = require('../services/calibration/calibrationInspector');
const { sha256 } = require('../services/util/hash');
const { startTestServer, readSample, ORIGIN } = require('./helpers');

// Copied verbatim from the hand-eye matrix supplied by the user in the task prompt (the original
// attachment was not available in this environment). Supplied data, not generated by this application.
const SUPPLIED_HAND_EYE_YAML = [
  '%YAML:1.0',
  '---',
  'info: "4 0 "',
  'handEyeMatrix: !!opencv-matrix',
  '   rows: 4',
  '   cols: 4',
  '   dt: f',
  '   data: [ 5.20042360e-01, -3.76300484e-01, 7.66781509e-01,',
  '       6.31424316e+02, 8.52015495e-01, 2.91824520e-01, -4.34635490e-01,',
  '       8.10536682e+02, -6.02121167e-02, 8.79338622e-01, 4.72374976e-01,',
  '       6.82570953e+01, 0., 0., 0., 1. ]',
  '',
].join('\n');

// SYNTHETIC stand-in for the unavailable Cfig companion: field names and approximate values follow the
// description in the task prompt. Its structure (nesting) is an assumption made for this test only.
const SYNTHETIC_CFIG = JSON.stringify({ FrameScale: 0.1, RobotPose: { position: { x: 459.55, y: 158.01, z: 845.29 }, orientation: { alfa: 0.556, beta: 0.103, gamma: 0.789, theta: 0.238 } } });

const yaml = (lines) => Buffer.from(['%YAML:1.0', '---', ...lines, ''].join('\n'));
const matrixYaml = (values, { rows = 4, cols = 4, dt = 'd' } = {}) => yaml([
  'm: !!opencv-matrix', `   rows: ${rows}`, `   cols: ${cols}`, `   dt: ${dt}`, `   data: [ ${values.join(', ')} ]`,
]);

test('supplied hand-eye matrix: parsed, numerically consistent, and still not a validated calibration', () => {
  const buf = Buffer.from(SUPPLIED_HAND_EYE_YAML);
  const r = inspectCalibrationFile({ content: buf, displayName: 'handeye.yml' });
  assert.equal(r.parse.ok, true, JSON.stringify(r.parse.diagnostics));
  assert.equal(r.file.sha256, sha256(buf));
  assert.equal(r.candidateTransformKey, 'handEyeMatrix');
  assert.equal(r.numericalCheck, 'passed');
  const m = r.matrices[0];
  assert.equal(m.dtName, 'float32');
  assert.deepEqual(m.matrix[3], [0, 0, 0, 1]);
  // Recomputed; prior independent figures: det 0.9999999927, ‖RᵀR−I‖_F ≈ 5.65e-8.
  assert.ok(Math.abs(m.metrics.determinant - 0.9999999927) < 5e-10, String(m.metrics.determinant));
  assert.ok(Math.abs(m.metrics.orthogonalityFrobenius - 5.65e-8) < 5e-10, String(m.metrics.orthogonalityFrobenius));
  assert.deepEqual(m.metrics.translation, [631.424316, 810.536682, 68.2570953]);
  assert.equal(m.metrics.translationUnits, 'unknown');
  assert.ok(m.precisionNote && /float32/.test(m.precisionNote));
  // Nothing physical is inferred or activated.
  assert.equal(r.physicalCalibrationStatus, 'not_validated');
  assert.equal(r.activation.status, 'disabled');
  assert.ok(r.activation.missingForActivation.length >= 8);
  for (const k of ['sourceFrame', 'destinationFrame', 'direction', 'translationUnits', 'calibrationIdentity', 'captureDate']) assert.equal(r.unresolved[k], null, k);
  assert.deepEqual(r.unresolved.infoField, { raw: '4 0 ', meaning: 'unknown' });
  assert.equal(r.unresolved.exportAlreadyTransformed, 'unknown');
});

test('synthetic Cfig stand-in: values listed, orientation fields NOT treated as a quaternion', () => {
  const r = inspectCalibrationFile({ content: Buffer.from(SUPPLIED_HAND_EYE_YAML), displayName: 'handeye.yml', companions: [{ content: Buffer.from(SYNTHETIC_CFIG), displayName: 'Cfig' }] });
  const c = r.companions[0];
  assert.equal(c.parse, 'ok');
  assert.ok(c.observations.some((o) => o.field === 'FrameScale' && o.value === 0.1));
  const orient = c.observations.find((o) => o.euclideanNorm !== undefined);
  assert.ok(orient);
  assert.ok(Math.abs(orient.euclideanNorm - Math.hypot(0.556, 0.103, 0.789, 0.238)) < 1e-12);
  assert.match(orient.note, /NOT treated as a quaternion/);
  assert.match(c.interpretation, /Not interpreted/);
  const bad = inspectCalibrationFile({ content: Buffer.from(SUPPLIED_HAND_EYE_YAML), displayName: 'h.yml', companions: [{ content: Buffer.from('{not json'), displayName: 'Cfig' }] });
  assert.equal(bad.companions[0].parse, 'failed');
});

test('strict YAML subset: unsafe or unsupported constructs are rejected with line numbers', () => {
  const cases = [
    [Buffer.from('---\nm: 1\n'), 'CALIB_DIRECTIVE'],
    [Buffer.from('%YAML:1.2\n---\nm: 1\n'), 'CALIB_DIRECTIVE'],
    [yaml(['m: !!python/object:os.system', '   rows: 4']), 'CALIB_UNSUPPORTED_TAG'],
    [yaml(['m: !ruby/object Foo']), 'CALIB_UNSUPPORTED_TAG'],
    [yaml(['a: &anchor 1']), 'CALIB_UNSUPPORTED_SYNTAX'],
    [yaml(['a: *anchor']), 'CALIB_UNSUPPORTED_SYNTAX'],
    [yaml(['<<: 1']), 'CALIB_UNSUPPORTED_SYNTAX'],
    [yaml(['a: 1', '---', 'b: 2']), 'CALIB_MULTIPLE_DOCUMENTS'],
    [yaml(['a:', '   b: 1']), 'CALIB_UNSUPPORTED_SYNTAX'],
    [yaml(['a: { b: 1 }']), 'CALIB_UNSUPPORTED_SYNTAX'],
    [yaml(['a: 1', 'a: 2']), 'CALIB_DUPLICATE_KEY'],
    [yaml(['a: .nan']), 'CALIB_NON_FINITE'],
    [yaml(['m: !!opencv-matrix', '   rows: 1', '   cols: 2', '   dt: d', '   data: [ 1., .inf ]']), 'CALIB_NON_FINITE'],
    [yaml(['m: !!opencv-matrix', '   rows: 1', '   cols: 2', '   dt: d', '   data: [ 1., 0x10 ]']), 'CALIB_MALFORMED_NUMBER'],
    [yaml(['m: !!opencv-matrix', '   rows: 1', '   cols: 2', '   dt: 3f', '   data: [ 1., 2. ]']), 'CALIB_MATRIX_TYPE'],
    [yaml(['m: !!opencv-matrix', '   rows: 1', '   cols: 2', '   dt: d', '   data: [ 1., 2.']), 'CALIB_MATRIX_DATA'],
    [yaml(['m: !!opencv-matrix', '   rows: 1', '   dt: d', '   data: [ 1. ]']), 'CALIB_MATRIX_FIELD'],
    [yaml(['a: "esc\\"aped"']), 'CALIB_STRING'],
    [Buffer.from(''), 'CALIB_EMPTY'],
    [Buffer.alloc(70 * 1024, 0x20), 'CALIB_TOO_LARGE'],
    [Buffer.from('%YAML:1.0\n---\na: \n'), 'CALIB_CONTROL_CHARACTERS'],
  ];
  for (const [buf, code] of cases) {
    const r = parseOpenCvYaml(buf);
    assert.equal(r.ok, false, `${code}: ${buf.toString('utf-8').slice(0, 60)}`);
    assert.equal(r.diagnostics[0].code, code, `${JSON.stringify(r.diagnostics)} for ${buf.toString('utf-8').slice(0, 60)}`);
  }
  assert.ok(parseOpenCvYaml(yaml(['m: !!python/object:os.system'])).diagnostics[0].line === 3);
});

test('numerical checks: shape, type, count, bottom row, reflection and non-orthogonal matrices fail', () => {
  const I = [1, 0, 0, 10, 0, 1, 0, 20, 0, 0, 1, 30, 0, 0, 0, 1];
  const ok = inspectCalibrationFile({ content: matrixYaml(I), displayName: 'i.yml' });
  assert.equal(ok.numericalCheck, 'passed');
  const failed = (buf) => inspectCalibrationFile({ content: buf, displayName: 'x.yml' }).matrices[0].checks.filter((c) => c.status === 'failed').map((c) => c.id);
  // A 3×3 matrix fails the shape check and, having 9 elements, the exactly-16 check too.
  assert.deepEqual(failed(matrixYaml([1, 0, 0, 0, 1, 0, 0, 0, 1], { rows: 3, cols: 3 })), ['dimensions_4x4', 'element_count']);
  assert.ok(failed(matrixYaml(I, { dt: 'i' })).includes('numeric_type'));
  assert.ok(failed(matrixYaml(I.slice(0, 15))).includes('element_count'));
  assert.deepEqual(failed(matrixYaml([...I.slice(0, 12), 0, 0, 0.5, 1])), ['bottom_row']);
  assert.deepEqual(failed(matrixYaml([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1])), ['rotation_proper']);
  assert.ok(failed(matrixYaml([2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1])).includes('rotation_orthogonal'));
  const two = inspectCalibrationFile({ content: yaml(['a: !!opencv-matrix', '   rows: 4', '   cols: 4', '   dt: d', `   data: [ ${I.join(', ')} ]`, 'b: !!opencv-matrix', '   rows: 4', '   cols: 4', '   dt: d', `   data: [ ${I.join(', ')} ]`]), displayName: 'two.yml' });
  assert.equal(two.numericalCheck, 'ambiguous_multiple_4x4_matrices');
  // Even a perfect identity is never "validated".
  assert.equal(ok.physicalCalibrationStatus, 'not_validated');
});

test('API: calibration import preserves exact bytes, is bounded and protected, and never changes job geometry', async (t) => {
  const s = await startTestServer();
  t.after(() => s.close());
  const form = (files) => {
    const f = new FormData();
    for (const [field, name, content] of files) f.append(field, new Blob([content]), name);
    return f;
  };
  const post = (body, headers = { Origin: ORIGIN, 'X-VD-CSRF': s.csrfToken }) => fetch(`${s.base}/calibrations`, { method: 'POST', headers, body }).then(async (r) => ({ status: r.status, body: await r.json() }));

  assert.equal((await post(form([['calibration', 'h.yml', SUPPLIED_HAND_EYE_YAML]]), { Origin: ORIGIN })).status, 403, 'CSRF token required');
  assert.equal((await post(form([['calibration', 'h.yml', SUPPLIED_HAND_EYE_YAML]]), { Origin: 'https://evil.example', 'X-VD-CSRF': s.csrfToken })).status, 403, 'origin allowlist');
  assert.equal((await post(form([['calibration', 'h.exe', 'MZ']]))).status, 415);
  assert.equal((await post(form([['calibration', 'big.yml', 'x'.repeat(70 * 1024)]]))).status, 413);
  assert.equal((await post(form([['other', 'h.yml', SUPPLIED_HAND_EYE_YAML]]))).status, 400);

  const created = await post(form([['calibration', 'handeye.yml', SUPPLIED_HAND_EYE_YAML], ['cfig', 'Cfig', SYNTHETIC_CFIG]]));
  assert.equal(created.status, 201, JSON.stringify(created.body));
  const id = created.body.calibration.id;
  assert.match(id, /^cal_[a-f0-9]{24}$/);
  assert.equal(created.body.inspection.numericalCheck, 'passed');
  assert.equal(created.body.inspection.activation.status, 'disabled');
  const stored = fs.readFileSync(path.join(s.config.dataDir, 'calibrations', id, 'content'));
  assert.equal(Buffer.compare(stored, Buffer.from(SUPPLIED_HAND_EYE_YAML)), 0, 'exact original bytes');
  assert.equal((await s.client.get(`/calibrations/${id}`)).body.inspection.companions.length, 1);
  assert.equal((await s.client.get('/calibrations')).body.calibrations[0].physicalCalibrationStatus, 'not_validated');
  assert.equal((await s.client.get('/calibrations/cal_..%2f..')).status, 404);

  // Referencing the calibration changes identity but not geometry or module bytes; nothing is applied.
  const project = await s.helpers.project();
  const src = await s.helpers.uploadText('straight.txt', readSample('Feature_Straight_Sample.txt'));
  const plain = (await s.client.post('/jobs', { projectId: project.id, sourceId: src.id })).body;
  const ref = await s.client.post('/jobs', { projectId: project.id, sourceId: src.id, parameters: { calibrationReference: { calibrationId: id } } });
  assert.equal(ref.status, 201, JSON.stringify(ref.body));
  assert.deepEqual(ref.body.record.path.waypoints, plain.record.path.waypoints);
  assert.equal(ref.body.record.output.sha256, plain.record.output.sha256);
  assert.notEqual(ref.body.record.configurationSha256, plain.record.configurationSha256);
  assert.equal(ref.body.record.coordinates.calibrationReference.applied, false);
  assert.equal(ref.body.record.coordinates.calibrationReference.physicalCalibrationStatus, 'not_validated');
  assert.equal(ref.body.gates.validation.calibrationTransform, 'not_applied');
  const unknown = await s.client.post('/jobs', { projectId: project.id, sourceId: src.id, parameters: { calibrationReference: { calibrationId: `cal_${'0'.repeat(24)}` } } });
  assert.equal(unknown.status, 422);
  assert.ok(unknown.body.error.diagnostics.some((d) => d.code === 'PARAM_CALIBRATION_UNKNOWN'));
});
