/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#646468",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e8f2",
        "surface-tint": "#005bc0",
        "primary-container": "#1a73e8",
        "inverse-surface": "#2d3038",
        "tertiary-fixed": "#ffdbcb",
        "primary-fixed": "#d8e2ff",
        "background": "#f9f9ff",
        "on-primary-fixed": "#001a41",
        "surface-container": "#ecedf7",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-surface": "#191c23",
        "on-tertiary-fixed-variant": "#783100",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#0e0200",
        "surface-dim": "#d8d9e3",
        "on-secondary-fixed-variant": "#46474a",
        "surface-variant": "#e0e2ec",
        "on-background": "#191c23",
        "secondary": "#5e5e62",
        "on-tertiary": "#ffffff",
        "tertiary": "#9e4300",
        "surface-container-low": "#f2f3fd",
        "primary-fixed-dim": "#adc7ff",
        "primary": "#005bbf",
        "on-secondary-fixed": "#1a1b1e",
        "tertiary-fixed-dim": "#ffb691",
        "on-primary-fixed-variant": "#004493",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eff0fa",
        "surface-container-highest": "#e0e2ec",
        "tertiary-container": "#c55500",
        "error": "#ba1a1a",
        "on-primary-container": "#ffffff",
        "secondary-fixed-dim": "#c7c6ca",
        "outline-variant": "#c1c6d6",
        "on-tertiary-fixed": "#341100",
        "on-surface-variant": "#414754",
        "secondary-fixed": "#e3e2e6",
        "inverse-primary": "#adc7ff",
        "surface-bright": "#f9f9ff",
        "surface": "#f9f9ff",
        "outline": "#727785",
        "secondary-container": "#e3e2e6"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "margin-desktop": "24px",
        "max-content-width": "1600px",
        "margin-mobile": "16px",
        "gutter": "16px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      }
    },
  },
  plugins: [],
};
