// Generated by test/make-fixtures.cjs from the backend pipeline. Do not edit by hand.
export const STRAIGHT_RECORD = {
  "mode": "file_import",
  "source": {
    "id": "src_demo_000000000000000000000000",
    "sha256": "7c37564f9c3eebb65a9de4efc41cec82e00fcf1b6912c3aa9f3ddcc4497ccc76",
    "kind": "demo",
    "displayName": "Feature_Straight_Sample.txt"
  },
  "geometry": {
    "requestedType": "straight",
    "plannedType": "straight",
    "startPoint": {
      "x": 414.69,
      "y": 1112.75,
      "z": 320.342
    },
    "endPoint": {
      "x": 338.531,
      "y": 1333.74,
      "z": 322.068
    },
    "viaPoint": null,
    "seamWidthMm": 5.54,
    "seamWidthProvenance": "file",
    "chordLengthMm": 233.75147583919122,
    "lengthMm": 233.75147583919122,
    "slopeDeg": 0.42307075814223855,
    "arc": null,
    "homeZ": {
      "formula": "max weld-geometry Z + homeLiftMm",
      "maxWeldZMm": 322.068,
      "homeLiftMm": 350
    },
    "offsetConvention": "XY components of the 3D unit travel tangent scaled by the back-off/forward distance; lateral offset along the tangent turned +90° about Z in the XY plane; scalar Z lift. Not collision-checked.",
    "conversion": null
  },
  "path": {
    "waypoints": [
      {
        "name": "home",
        "type": "home",
        "pos": [
          319.8846,
          1203.6958,
          672.068
        ],
        "orient": [
          0,
          0.382683431,
          0.923879533,
          0
        ],
        "conf": [
          0,
          0,
          0,
          0
        ],
        "speed": "v100",
        "zone": "z100"
      },
      {
        "name": "Target_30",
        "type": "approach",
        "pos": [
          389.7452,
          1077.7111,
          365.342
        ],
        "orient": [
          0.383667588,
          0.149822324,
          0.889291982,
          -0.198776819
        ],
        "conf": [
          0,
          0,
          0,
          0
        ],
        "speed": "v60",
        "zone": "z10"
      },
      {
        "name": "Target_40",
        "type": "weld_start",
        "pos": [
          414.69,
          1112.75,
          320.342
        ],
        "orient": [
          0.383667588,
          0.149822324,
          0.889291982,
          -0.198776819
        ],
        "conf": [
          0,
          0,
          0,
          0
        ],
        "speed": "v100",
        "zone": "fine"
      },
      {
        "name": "Target_20_5",
        "type": "weld_end",
        "pos": [
          338.531,
          1333.74,
          322.068
        ],
        "orient": [
          0.383667588,
          0.149822324,
          0.889291982,
          -0.198776819
        ],
        "conf": [
          0,
          0,
          0,
          0
        ],
        "speed": "v100",
        "zone": "fine"
      },
      {
        "name": "Target_20",
        "type": "retract",
        "pos": [
          298.9247,
          1341.2444,
          367.068
        ],
        "orient": [
          0.383667588,
          0.149822324,
          0.889291982,
          -0.198776819
        ],
        "conf": [
          0,
          0,
          0,
          0
        ],
        "speed": "v80",
        "zone": "z10"
      }
    ],
    "segments": [
      {
        "index": 0,
        "instruction": "MoveJ",
        "role": "air",
        "from": null,
        "to": "home",
        "speed": "v100",
        "zone": "z100"
      },
      {
        "index": 1,
        "instruction": "MoveL",
        "role": "air",
        "from": "home",
        "to": "Target_30",
        "speed": "v60",
        "zone": "z10"
      },
      {
        "index": 2,
        "instruction": "MoveL",
        "role": "approach",
        "from": "Target_30",
        "to": "Target_40",
        "speed": "v100",
        "zone": "fine"
      },
      {
        "index": 3,
        "instruction": "MoveL",
        "role": "weld",
        "from": "Target_40",
        "to": "Target_20_5",
        "speed": "v100",
        "zone": "fine"
      },
      {
        "index": 4,
        "instruction": "MoveL",
        "role": "retract",
        "from": "Target_20_5",
        "to": "Target_20",
        "speed": "v80",
        "zone": "z10"
      },
      {
        "index": 5,
        "instruction": "MoveL",
        "role": "air",
        "from": "Target_20",
        "to": "home",
        "speed": "v100",
        "zone": "fine"
      }
    ],
    "targetCount": 5,
    "instructionCount": 6
  },
  "output": {
    "sha256": "30791efbb5d8e7221752f79869e1f31898226934dbcd84c84414d8a1b25fe613"
  }
};

export const ARC_RECORD = {
  "mode": "file_import",
  "source": {
    "id": "src_demo_000000000000000000000000",
    "sha256": "7992b54e5a7f64107a891b83ef11c8d32b0d72d1323035da37d7e7de2a57e716",
    "kind": "demo",
    "displayName": "Feature_Arc_Sample.txt"
  },
  "geometry": {
    "requestedType": "arc",
    "plannedType": "arc",
    "startPoint": {
      "x": 1133.5288,
      "y": -38.2234,
      "z": 480.278
    },
    "endPoint": {
      "x": 980,
      "y": 110,
      "z": 480.278
    },
    "viaPoint": {
      "x": 1080,
      "y": 60,
      "z": 480.278
    },
    "seamWidthMm": 5.54,
    "seamWidthProvenance": "file",
    "chordLengthMm": 213.40400356366328,
    "lengthMm": 227.15026606303906,
    "slopeDeg": null,
    "arc": {
      "center": {
        "x": 950.3136807924824,
        "y": -74.37263841503534,
        "z": 480.278
      },
      "radiusMm": 186.7472820263041,
      "normal": {
        "x": 0,
        "y": 0,
        "z": 1
      },
      "sweepDeg": 69.69178570884203,
      "viaAngleDeg": 34.855359146721874,
      "arcLengthMm": 227.15026606303906,
      "viaBowMm": 33.48531368048216,
      "maxChordDeviationMm": 33.48531622930029,
      "planeTiltDeg": 0,
      "direction": "counterclockwise_from_above",
      "start": {
        "x": 1133.5288,
        "y": -38.2234,
        "z": 480.278
      },
      "samples": [
        {
          "x": 1133.5288,
          "y": -38.2234,
          "z": 480.278
        },
        {
          "x": 1132.5540303909702,
          "y": -33.5927129316202,
          "z": 480.278
        },
        {
          "x": 1131.4622416842135,
          "y": -28.98821122831437,
          "z": 480.278
        },
        {
          "x": 1130.2541349326505,
          "y": -24.412851505541113,
          "z": 480.278
        },
        {
          "x": 1128.9304858786584,
          "y": -19.869571666282482,
          "z": 480.278
        },
        {
          "x": 1127.492144455956,
          "y": -15.361289014575064,
          "z": 480.278
        },
        {
          "x": 1125.9400342438482,
          "y": -10.890898382267906,
          "z": 480.278
        },
        {
          "x": 1124.2751518741848,
          "y": -6.461270270210207,
          "z": 480.278
        },
        {
          "x": 1122.4985663914067,
          "y": -2.0752490050622328,
          "z": 480.278
        },
        {
          "x": 1120.611418566099,
          "y": 2.264349087086913,
          "z": 480.278
        },
        {
          "x": 1118.6149201624858,
          "y": 6.554737489122033,
          "z": 480.278
        },
        {
          "x": 1116.5103531603386,
          "y": 10.793161282163652,
          "z": 480.278
        },
        {
          "x": 1114.2990689318003,
          "y": 14.976898914540385,
          "z": 480.278
        },
        {
          "x": 1111.9824873736486,
          "y": 19.10326394933557,
          "z": 480.278
        },
        {
          "x": 1109.562095995562,
          "y": 23.169606789386307,
          "z": 480.278
        },
        {
          "x": 1107.039448964967,
          "y": 27.173316378627106,
          "z": 480.278
        },
        {
          "x": 1104.416166109087,
          "y": 31.111821878685845,
          "z": 480.278
        },
        {
          "x": 1101.6939318748266,
          "y": 34.98259431965539,
          "z": 480.278
        },
        {
          "x": 1098.8744942471665,
          "y": 38.783148223980675,
          "z": 480.278
        },
        {
          "x": 1095.959663626756,
          "y": 42.51104320241899,
          "z": 480.278
        },
        {
          "x": 1092.9513116674304,
          "y": 46.1638855210483,
          "z": 480.278
        },
        {
          "x": 1089.8513700743947,
          "y": 49.73932963831753,
          "z": 480.278
        },
        {
          "x": 1086.6618293638492,
          "y": 53.23507971115187,
          "z": 480.278
        },
        {
          "x": 1083.3847375848509,
          "y": 56.64889106914603,
          "z": 480.278
        },
        {
          "x": 1080.0221990042319,
          "y": 59.97857165589858,
          "z": 480.278
        },
        {
          "x": 1076.5763727554204,
          "y": 63.22198343656248,
          "z": 480.278
        },
        {
          "x": 1073.0494714520305,
          "y": 66.37704377070736,
          "z": 480.278
        },
        {
          "x": 1069.4437597671117,
          "y": 69.44172674961209,
          "z": 480.278
        },
        {
          "x": 1065.761552978971,
          "y": 72.41406449712966,
          "z": 480.278
        },
        {
          "x": 1062.0052154844989,
          "y": 75.29214843328793,
          "z": 480.278
        },
        {
          "x": 1058.1771592809584,
          "y": 78.07413049981585,
          "z": 480.278
        },
        {
          "x": 1054.279842417206,
          "y": 80.75822434680776,
          "z": 480.278
        },
        {
          "x": 1050.3157674153451,
          "y": 83.34270647976376,
          "z": 480.278
        },
        {
          "x": 1046.2874796638202,
          "y": 85.82591736626989,
          "z": 480.278
        },
        {
          "x": 1042.197565782988,
          "y": 88.20626250160728,
          "z": 480.278
        },
        {
          "x": 1038.0486519642118,
          "y": 90.48221343260607,
          "z": 480.278
        },
        {
          "x": 1033.843402283546,
          "y": 92.65230873908686,
          "z": 480.278
        },
        {
          "x": 1029.5845169910974,
          "y": 94.71515497225897,
          "z": 480.278
        },
        {
          "x": 1025.2747307771542,
          "y": 96.66942754947377,
          "z": 480.278
        },
        {
          "x": 1020.9168110162047,
          "y": 98.51387160475792,
          "z": 480.278
        },
        {
          "x": 1016.5135559899657,
          "y": 100.24730279458026,
          "z": 480.278
        },
        {
          "x": 1012.0677930905673,
          "y": 101.86860805833564,
          "z": 480.278
        },
        {
          "x": 1007.5823770050442,
          "y": 103.37674633305679,
          "z": 480.278
        },
        {
          "x": 1003.060187882301,
          "y": 104.77074922189556,
          "z": 480.278
        },
        {
          "x": 998.5041294837278,
          "y": 106.04972161594424,
          "z": 480.278
        },
        {
          "x": 993.9171273186543,
          "y": 107.21284226899743,
          "z": 480.278
        },
        {
          "x": 989.3021267658388,
          "y": 108.25936432488601,
          "z": 480.278
        },
        {
          "x": 984.6620911821993,
          "y": 109.18861579704384,
          "z": 480.278
        },
        {
          "x": 980,
          "y": 109.99999999999994,
          "z": 480.278
        }
      ],
      "sampling": "48 equal-angle segments on the fitted circle (display only; the controller interpolates MoveC itself)"
    },
    "homeZ": {
      "formula": "max weld-geometry Z (exact arc maximum) + homeLiftMm",
      "maxWeldZMm": 480.278,
      "homeLiftMm": 350
    },
    "offsetConvention": "XY components of the 3D unit travel tangent scaled by the back-off/forward distance; lateral offset along the tangent turned +90° about Z in the XY plane; scalar Z lift. Not collision-checked.",
    "conversion": null
  },
  "path": {
    "waypoints": [
      {
        "name": "home",
        "type": "home",
        "pos": [
          1015.0904,
          -7.2774,
          830.278
        ],
        "orient": [
          0,
          0.382683431,
          0.923879533,
          0
        ],
        "conf": [
          0,
          0,
          0,
          0
        ],
        "speed": "v100",
        "zone": "z100"
      },
      {
        "name": "Target_30",
        "type": "approach",
        "pos": [
          1104.0301,
          -69.5256,
          525.278
        ],
        "orient": [
          0.383667588,
          0.149822324,
          0.889291982,
          -0.198776819
        ],
        "conf": [
          0,
          0,
          0,
          0
        ],
        "speed": "v60",
        "zone": "z10"
      },
      {
        "name": "Target_40",
        "type": "weld_start",
        "pos": [
          1133.5288,
          -38.2234,
          480.278
        ],
        "orient": [
          0.383667588,
          0.149822324,
          0.889291982,
          -0.198776819
        ],
        "conf": [
          0,
          0,
          0,
          0
        ],
        "speed": "v100",
        "zone": "fine"
      },
      {
        "name": "Target_45",
        "type": "weld_via",
        "pos": [
          1080,
          60,
          480.278
        ],
        "orient": [
          0.425589621,
          -0.123399663,
          0.893341749,
          -0.074743004
        ],
        "conf": [
          0,
          0,
          0,
          0
        ],
        "speed": null,
        "zone": null
      },
      {
        "name": "Target_20_5",
        "type": "weld_end",
        "pos": [
          980,
          110,
          480.278
        ],
        "orient": [
          0.428448181,
          -0.385157792,
          0.815438798,
          0.056082067
        ],
        "conf": [
          0,
          0,
          0,
          0
        ],
        "speed": "v100",
        "zone": "fine"
      },
      {
        "name": "Target_20",
        "type": "retract",
        "pos": [
          954.6905,
          78.6244,
          525.278
        ],
        "orient": [
          0.428448181,
          -0.385157792,
          0.815438798,
          0.056082067
        ],
        "conf": [
          0,
          0,
          0,
          0
        ],
        "speed": "v80",
        "zone": "z10"
      }
    ],
    "segments": [
      {
        "index": 0,
        "instruction": "MoveJ",
        "role": "air",
        "from": null,
        "to": "home",
        "speed": "v100",
        "zone": "z100"
      },
      {
        "index": 1,
        "instruction": "MoveL",
        "role": "air",
        "from": "home",
        "to": "Target_30",
        "speed": "v60",
        "zone": "z10"
      },
      {
        "index": 2,
        "instruction": "MoveL",
        "role": "approach",
        "from": "Target_30",
        "to": "Target_40",
        "speed": "v100",
        "zone": "fine"
      },
      {
        "index": 3,
        "instruction": "MoveC",
        "role": "weld",
        "from": "Target_40",
        "to": "Target_20_5",
        "speed": "v100",
        "zone": "fine",
        "via": "Target_45"
      },
      {
        "index": 4,
        "instruction": "MoveL",
        "role": "retract",
        "from": "Target_20_5",
        "to": "Target_20",
        "speed": "v80",
        "zone": "z10"
      },
      {
        "index": 5,
        "instruction": "MoveL",
        "role": "air",
        "from": "Target_20",
        "to": "home",
        "speed": "v100",
        "zone": "fine"
      }
    ],
    "targetCount": 6,
    "instructionCount": 6
  },
  "output": {
    "sha256": "45e748b1fb5486493f1a147c40930ccbdad1ebb23e9f6608a04ad38c58ab9471"
  }
};
