/**
 * Read-only facts from the archived RobotStudio Pack&Go (auto_calib.rspag).
 *
 * The archive is a ZIP. Only two RAPID modules are decompressed; every other
 * entry is reported by category and count, never by content, because the
 * archive also carries virtual-controller licence files and controller backup
 * data that should not be displayed or redistributed.
 *
 * This describes a pre-existing, station-specific pose routine. It is not
 * generated by this application, and nothing here captures images, reads robot
 * poses, solves a hand-eye transform or measures calibration error.
 */

const fs = require('fs');
const zlib = require('zlib');
const { sha256 } = require('../util/hash');

const MAX_ENTRY_BYTES = 1024 * 1024;
const MODULE_ENTRY = 'Backups/Controller2/RAPID/TASK1/PROGMOD/Module1.modx';
const CALIBDATA_ENTRY = 'Backups/Controller2/RAPID/TASK1/PROGMOD/CalibData.modx';

function readZipIndex(buf) {
  const minStart = Math.max(0, buf.length - 65557);
  let eocd = -1;
  for (let i = buf.length - 22; i >= minStart; i -= 1) {
    if (buf.readUInt32LE(i) === 0x06054b50) { eocd = i; break; }
  }
  if (eocd < 0) throw new Error('rspag: end of central directory not found');
  const entries = buf.readUInt16LE(eocd + 10);
  let offset = buf.readUInt32LE(eocd + 16);
  const index = new Map();
  for (let n = 0; n < entries; n += 1) {
    if (buf.readUInt32LE(offset) !== 0x02014b50) throw new Error('rspag: bad central directory entry');
    const method = buf.readUInt16LE(offset + 10);
    const compressedSize = buf.readUInt32LE(offset + 20);
    const size = buf.readUInt32LE(offset + 24);
    const nameLen = buf.readUInt16LE(offset + 28);
    const extraLen = buf.readUInt16LE(offset + 30);
    const commentLen = buf.readUInt16LE(offset + 32);
    const localOffset = buf.readUInt32LE(offset + 42);
    const name = buf.toString('utf-8', offset + 46, offset + 46 + nameLen);
    index.set(name, { method, compressedSize, size, localOffset });
    offset += 46 + nameLen + extraLen + commentLen;
  }
  return index;
}

function readEntry(buf, entry) {
  if (entry.size > MAX_ENTRY_BYTES) throw new Error('rspag: entry too large');
  const lo = entry.localOffset;
  if (buf.readUInt32LE(lo) !== 0x04034b50) throw new Error('rspag: bad local header');
  const start = lo + 30 + buf.readUInt16LE(lo + 26) + buf.readUInt16LE(lo + 28);
  const data = buf.subarray(start, start + entry.compressedSize);
  if (entry.method === 0) return data.toString('utf-8');
  if (entry.method === 8) return zlib.inflateRawSync(data, { maxOutputLength: MAX_ENTRY_BYTES }).toString('utf-8');
  throw new Error(`rspag: unsupported compression ${entry.method}`);
}

function parseRoutine(text) {
  const clean = text.replace(/^﻿/, '');
  const targets = [...clean.matchAll(/CONST robtarget (\w+):=\[\[[^\]]*\],\[[^\]]*\],\[([^\]]*)\]/g)].map((m) => ({ name: m[1], configuration: m[2] }));
  const mainBody = (clean.match(/PROC main\(\)([\s\S]*?)ENDPROC/) || [])[1] || '';
  const steps = [];
  for (const line of mainBody.split(/\r?\n/).map((l) => l.trim()).filter(Boolean)) {
    const mv = line.match(/^(MoveL|MoveJ|MoveC)\s+(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\\WObj:=(\w+);$/);
    const wt = line.match(/^WaitTime\s+([\d.]+);$/);
    if (mv) steps.push({ kind: 'move', instruction: mv[1], target: mv[2], speed: mv[3], zone: mv[4], tool: mv[5], wobj: mv[6] });
    else if (wt) steps.push({ kind: 'wait', seconds: Number(wt[1]) });
    else steps.push({ kind: 'other', text: line.slice(0, 80) });
  }
  const moves = steps.filter((s) => s.kind === 'move');
  const visits = new Map();
  for (const m of moves) visits.set(m.target, (visits.get(m.target) || 0) + 1);
  return { targets, steps, moves, visits };
}

function parseTooldata(text) {
  const m = text.match(/PERS tooldata (\w+):=\[(TRUE|FALSE),\[\[([^\]]*)\],\[([^\]]*)\]\],\[([\d.]+),/);
  if (!m) return null;
  return { name: m[1], robhold: m[2] === 'TRUE', translationMm: m[3].split(',').map(Number), orientation: m[4].split(',').map(Number), massKg: Number(m[5]) };
}

function readCalibrationArchive(archivePath) {
  const buf = fs.readFileSync(archivePath);
  const index = readZipIndex(buf);
  const names = [...index.keys()];
  const routine = parseRoutine(readEntry(buf, index.get(MODULE_ENTRY)));
  const tool = parseTooldata(readEntry(buf, index.get(CALIBDATA_ENTRY)));
  const waits = routine.steps.filter((s) => s.kind === 'wait');
  const nonHome = routine.targets.filter((t) => t.name.toLowerCase() !== 'home');
  const repeated = [...routine.visits.entries()].filter(([name, count]) => count > 1 && name.toLowerCase() !== 'home').map(([name, count]) => ({ target: name, visits: count }));

  return {
    archive: {
      fileName: 'auto_calib.rspag',
      sizeBytes: buf.length,
      sha256: sha256(buf),
      entryCount: names.filter((n) => !n.endsWith('/')).length,
      categories: {
        rapidModules: names.filter((n) => /\.modx?$/i.test(n)).length,
        licenceFiles: names.filter((n) => /\/License\//i.test(n) && !n.endsWith('/')).length,
        controllerBackupFiles: names.filter((n) => /\/(BACKINFO|SYSPAR|HOME|ADDINDATA)\//i.test(n) && !n.endsWith('/')).length,
      },
      sensitiveNote: 'The archive also contains virtual-controller licence files and controller backup data (including a passphrase file). They are not displayed. Do not redistribute the archive publicly.',
    },
    routine: {
      module: 'Module1 (PROC main)',
      robtargetCount: routine.targets.length,
      nonHomePoseCount: nonHome.length,
      poseNames: routine.targets.map((t) => t.name),
      motionStatementCount: routine.moves.length,
      motionInstructions: routine.moves.reduce((acc, m) => ({ ...acc, [m.instruction]: (acc[m.instruction] || 0) + 1 }), {}),
      distinctDestinations: routine.visits.size,
      repeatedDestinations: repeated,
      waitStatementCount: waits.length,
      waitSeconds: [...new Set(waits.map((w) => w.seconds))],
      programmedDwellSeconds: waits.reduce((a, w) => a + w.seconds, 0),
      dwellNote: 'Sum of WaitTime statements only. It excludes motion time and is not the duration of a calibration; dwells do not all correspond to unique poses.',
      tools: [...new Set(routine.moves.map((m) => m.tool))],
      workObjects: [...new Set(routine.moves.map((m) => m.wobj))],
      speeds: [...new Set(routine.moves.map((m) => m.speed))],
      configurationsUsed: [...new Set(routine.targets.map((t) => `[${t.configuration}]`))],
      steps: routine.steps.map((s, i) => ({ index: i + 1, ...s })),
    },
    tooldata: tool && {
      ...tool,
      note: 'Station-specific tooldata stored in the archive. It differs from other tool figures quoted in project documents (e.g. a [0,0,200] mm TCP in the report and [0,0,380] mm in the old README). Treat these as potentially different configurations; nothing here is applied to a robot.',
    },
  };
}

module.exports = { readCalibrationArchive, readZipIndex, parseRoutine };
